### ISSUE TITLE
MASTER fails to index stdlib

### ISSUE THREAD

**Issue by ldelossa** [puqeko/zig2dash#1]
```
node index.js                          
? Version (Use arrow keys)
❯ master 
? Version master
? Merge with existing './master/Zig.docset' or replace it? Replace
? Tasks Zig Standard Library, Zig Language Reference, Create Zig.tgz
[guide] https://ziglang.org/documentation/master/
[guide] Waiting for page load...
[guide] Replacing links to std lib
[guide] Guide	Keyword	Builtin	Type
[guide] 188	29	117	35
[guide] Finished!
[std] https://ziglang.org/documentation/master/std/#A;
[std] Waiting for page load...
file:///home/louis/git/zig/zig2dash/genstd.js:233
  let version = dom.window.zigAnalysis.params.zigVersion;
                                       ^

TypeError: Cannot read properties of undefined (reading 'params')
    at generate (file:///home/louis/git/zig/zig2dash/genstd.js:233:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async main (file:///home/louis/git/zig/zig2dash/index.js:58:47)

Node.js v22.11.0
```

This does not happen when building v0.11.0 docs:

```
node index.js                          
? Version (Use arrow keys)
❯ master 
? Version 0.11.0
? Tasks Zig Standard Library, Zig Language Reference, Create Zig.tgz
[guide] https://ziglang.org/documentation/0.11.0/
[guide] Waiting for page load...
[guide] Replacing links to std lib
[guide] Guide	Keyword	Builtin	Type
[guide] 185	28	118	35
[guide] Finished!
[std] https://ziglang.org/documentation/0.11.0/std/#A;
[std] Waiting for page load...
[std] Loaded version: 0.11.0
[std] Found library std
[std] Banner found
[std] Created style.css
[std] Created script.js
[std] Indexing types Type, Namespace, Global, Function, Value, Error
[std] Done 	404? 	Name
[std] 1107 	0 	std.HashMap.fetchPut
```
The above is just a snapshot of stdout as it indexes stdlib.

**Comment by puqeko** [comment]
Hey. I'll need to have a closer look but unfortunately I think this might be because of fundamental changes to how the zig docs are served. My hack for scraping the docs relied on emulating the browser environment with jsdom but I don't think this will work for the current versions of zig docs which includes wasm. Another approach may be needed

**Comment by puqeko** [comment]
It seems that since Zig 0.12.0 you can generate [fully interactive offline documentation with the `zig std` command](https://ziglang.org/download/0.12.0/release-notes.html#Installed-Standard-Library-Documentation) which is pretty neat! Therefore, I don't think it makes sense to continue maintaining this repo. You're welcome to fork and have a go at fixing it if you really really want Dash support.
